service: image-analysis

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

functions:
  img-analyse:
    handler: handler.main
    events:
      - http:
          path: analyse
          method: get
